### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by rreusser** [plotly/react-plotly.js#1]
- [x] remove class properties transform from src 😞 
- [x] have it look for `Plotly.react`
- [x] lint (using prettier)
- [x] set up build/lib for distribution
- [ ] add animation
- [x] frames
- [x] tests (added jest; needs lots more tests)
- [x] decide on handling of two-way binding (zoom, pan changing, e.g., `xaxis.range`)
- [x] take down temporary netlify site
- [x] publish to npm
- [x] production cleanup
- [x] test scripts on windows
- [ ] publish dummy repo to prevent typosquatting: `plotlyjs-react` or `plotly.js-react`, whichever doesn't get used.
- [x] close related issues: https://github.com/plotly/plotly.js/issues/1850 https://github.com/plotly/plotly.js/issues/204
